### ISSUE TITLE
Comments and Virtual Text same color

### ISSUE THREAD

**Issue by uthmanmoh** [catppuccin/nvim#679] opened 2024-03-16 00:50 UTC
### Description

As you can see in this screenshot, the color of the comments, LSP virtual text, and Copilot suggestions virtual text is all the same, which makes it pretty confusing. Is it possible to change one of these to a different color? Otherwise are there any suggestions to improve the readability of this?

<img width="1020" alt="image" src="https://github.com/catppuccin/nvim/assets/83053931/6d2286bd-c2a3-480e-bd3b-19d71a2abda7">

I'm using macciatto with the config from LazyVim:
```lua
{
    "catppuccin/nvim",
    lazy = true,
    name = "catppuccin",
    opts = {
      flavour = "macchiato",
      integrations = {
        aerial = true,
        alpha = true,
        cmp = true,
        dashboard = true,
        flash = true,
        gitsigns = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        leap = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        navic = { enabled = true, custom_bg = "lualine" },
        neotest = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },
    },
  },
```

### Neovim version

```markdown
NVIM v0.10.0-dev-2501+gdbf6be296-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
```

### Terminal and multiplexer

alacritty 0.13.1 with tmux 3.4

### Catppuccin version / branch / rev

  "catppuccin": { "branch": "main", "commit": "045e3499d9ec8d84635fb08877ae44fd33f6a38d" },

### Steps to reproduce

write a comment, get an LSP virtual suggestion open, and start copilot

### Expected behavior

being able to visually tell the difference between the 3 (or at least 2)

### Actual behavior

all 3 look the same and can't tell them apart

**Comment by fioncat** [comment] 2024-04-30 07:22
It looks different for me:

![image](https://github.com/catppuccin/nvim/assets/34646834/1f537e68-7301-46e9-aa13-f3b012ac0f37)

**Comment by fioncat** [comment] 2024-04-30 08:58
I took your config but it looks normal:

![image](https://github.com/catppuccin/nvim/assets/34646834/2e9479c3-14de-41c2-8153-31cc78550b2f)

What plugin are you using to display copilot suggestions?

**Comment by uthmanmoh** [comment] 2024-05-02 04:15
Here are my configs: https://github.com/uthmanmoh/nvim

I wonder if it's because of a different terminal font? Which font are you using? I'm using the Jetbrains Mono Nerd Font

**Comment by fioncat** [comment] 2024-05-16 02:33
I am using Source Code Pro.

But I don't think this is related to the font. Can you try a different terminal or try it outside of tmux?

**Comment by vollowx** [comment] 2024-08-07 02:51
Is the problem still unresolved? I suppose this isn't caused by this colorscheme b/c these highlights are colored differently. If it is, try to check your plugins (cmp, copilot, etc), and check what it look like in the default colorscheme.

**Comment by vollowx** [comment] 2024-08-07 02:53
I'm going to close this as the screenshot at your Neovim dotfiles repo looks pretty normal, but feel free to re-open :smile:

**Closed by vollowx** 2024-08-07 02:53 UTC
Labels: bug

**Comment by uthmanmoh** [comment] 2024-08-07 02:55
Yeah maybe it has to do with something else I'm not too sure. It's fine to resolve for now though thanks

**Comment by JoshuaCrewe** [comment] 2024-11-06 17:39
@uthmanmoh did you work out why this was happening for you in the end? I am experiencing the same problem I think

**Comment by uthmanmoh** [comment] 2024-11-06 18:09
Nope, just gave up
