### ISSUE TITLE
Attempt to index local 'file' (a nil value)

### ISSUE THREAD

**Issue by bwbuhse** [catppuccin/nvim#368] opened 2022-12-14 14:32 UTC
### Description

When starting neovim, I get "attempt to index local 'file' ( a nil value) at `.../packer/start/catppuccin/lua/catppuccin/lib/compiler.lua:76`

If I run `:Catppuccin mocha` after that, the theme loads fine.

This happened recently after running `:PackerUpdate` but I looked through the breaking changes and didn't notice anything that would seem relevant to my config (I could've just missed something, of course).

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch

### Catppuccin version / branch / rev

v0.2.7

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Let catppuccin install, then quit
3. `nvim -nu minimal.lua`

### Expected behavior

Catppuccin loads correctly

### Actual behavior

Catppuccin loading fails and only succeeds with `:Catppuccin <flavor>`

### Minimal config

```Lua
-- `minimal.lua` used for reproducible configuration
-- Open with `nvim --clean -u minimal.lua`

local is_windows = vim.fn.has("win32") == 1
local function join(...)
  local sep = is_windows and "\\" or "/"
  return table.concat({ ... }, sep)
end

local root_tmp = is_windows and os.getenv("TEMP") or "/tmp"
local site_path = join(root_tmp, "nvim", "site")
local pack_path = join(site_path, "pack")
local install_path = join(pack_path, "packer", "start", "packer.nvim")
local compile_path = join(install_path, "plugin", "packer_compiled.lua")
vim.opt.packpath = site_path

local function load_plugins()
  local packer = require("packer")
  local use = packer.use
  packer.reset()
  packer.init({ compile_path = compile_path, package_root = pack_path })

  use("wbthomason/packer.nvim")
  use({ "catppuccin/nvim", as = "catppuccin" })
  -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  packer.install()
end

_G.load_config = function()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("catppuccin").setup({
    flavour = "mocha"
  })

  vim.api.nvim_command("colorscheme catppuccin")
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by nullchilly** [comment] 2022-12-14 14:35
Minimal config please?

**Comment by bwbuhse** [comment] 2022-12-14 14:37
I re-created it with the template minimal config. First launch it works fine since it installs catppuccin first, but if I launch again after that I get 

`Error executing vim.schedule lua callback: /tmp/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:359: Vim(lua):E5108: Error executing lua .../packer/start/catppuccin/lua/catppuccin/lib/compiler.lua:76: attempt to index local 'file' (a nil value)`

**Comment by nullchilly** [comment] 2022-12-14 14:37
Can you post the output of

```lua
ls ~/.cache/nvim/catppuccin
```

**Comment by bwbuhse** [comment] 2022-12-14 14:38
```
Error executing vim.schedule lua callback: /tmp/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:359: Vim(lua):E5108: Error executing lua .../packer/start/catppuccin/lua/catppuccin/lib/compiler.lua:76: attempt to index local 'file' (a nil value)```

**Comment by nullchilly** [comment] 2022-12-14 14:42
I can't reproduce it with minimal.lua

Can you describe your environment more?

**Comment by nullchilly** [comment] 2022-12-14 14:49
@bwbuhse Can you update catppuccin then send the output

**Comment by bwbuhse** [comment] 2022-12-14 14:51
```Error while writing compiled file to /home/ben/.cache/nvim/catppuccin/macchiato_compiled.lua
Error while writing compiled file to /home/ben/.cache/nvim/catppuccin/latte_compiled.lua
Error while writing compiled file to /home/ben/.cache/nvim/catppuccin/mocha_compiled.lua
Error while writing compiled file to /home/ben/.cache/nvim/catppuccin/frappe_compiled.lua``` is the output... and that made me realize that for whatever reason, `~/.cache/nvim` is owned by root instead of my user. I have zero clue why, but I can try chowning it to myself

**Comment by nullchilly** [comment] 2022-12-14 14:52
Yeah seems like some read perrmission on your end?

**Comment by bwbuhse** [comment] 2022-12-14 14:54
Yup, apparently that was it. Thanks for the help! I legitimately have zero clue why it was owned by root.

Running `sudo chown -R ben ~/.cache/nvim/` solved it.

**Comment by nullchilly** [comment] 2022-12-14 14:54
Nice! Closing :)

**Closed by nullchilly** 2022-12-14 14:54 UTC
Labels: bug
